"""
Gera csv/leiloeiros_todos.csv com os leiloeiros REGULAR extraídos de todas
as juntas comerciais (JUCEA, JUCEAC, JUCEB, JUCEES, JUCEMAT, JUCEMG,
JUCEMS, JUCEPAR, JUCEPE, JUCEPI, JUCER, JUCERJA, JUCERN, JUCERR,
JUCESC, JUCESP, JUCETINS, JUCISDF, JUCISRS).

Apenas linhas com e-mail de domínio próprio são mantidas;
e-mails de serviços (gmail, hotmail, etc.) são descartados pelo scraper.
"""
from pathlib import Path
import csv

BASE_DIR = Path(r"c:\Users\arthur\OneDrive\Documentos\Cursor\leiloes")
CSV_DIR  = BASE_DIR / "csv"
CSV_DIR.mkdir(exist_ok=True)
OUT = CSV_DIR / "leiloeiros_todos.csv"

# Formato: (Nome, E-mail, Junta)
# Inclui TODOS os leiloeiros REGULAR — o scraper filtra por domínio
DATA = [
    # ── JUCEA ─────────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCEA"),
    ("Brian Galvão Frota","contato@amazonasleiloes.com.br","JUCEA"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEA"),
    ("Danielly Fernandes da Silva Nazareth","daniellylobos@hotmail.com","JUCEA"),
    ("Davi Borges De Aquino","inscricoes@alfaleiloes.com","JUCEA"),
    ("Deoniza Kiratch","deonizia@deonizialeiloes.com.br","JUCEA"),
    ("Fabio Prando Facundes Goes","fabiopfgoes@gmail.com","JUCEA"),
    ("JIMMY ASAMI","jimmy@asamileiloes.com.br","JUCEA"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEA"),
    ("Leonardo Vieira Amaral","leon.vieira@leilaonet.com.br","JUCEA"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCEA"),
    ("Mariana Govêa Lessa","marianagouvea@hotmail.com","JUCEA"),
    ("Ricardo Marcelo Gomes de Oliveira","ricardomgoliveiraad@hotmail.com","JUCEA"),
    ("Sandro De Oliveira","olsandro@yahoo.com.br","JUCEA"),
    ("Wesley Silva Ramos","wesleyleiloeiro@gmail.com","JUCEA"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCEA"),
    # ── JUCEAC ────────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","licitacoes@hoppeleiloes.com.br","JUCEAC"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEAC"),
    ("Deonizia Kiratch","deonizia@deonizialeiloes.com.br","JUCEAC"),
    ("Evanilde Aquino Pimentel Rosa","contato@rondonialeiloes.com.br","JUCEAC"),
    ("Felipe Cezar Sousa E Silva","leiloesaguiar@gmail.com","JUCEAC"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCEAC"),
    ("Flavia Correa Duarte Feitosa","flavia.duarte.leiloeira@gmail.com","JUCEAC"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEAC"),
    ("Josecelli Kildare Fraga Gomes","kildare.gomes@hotmail.com","JUCEAC"),
    ("Júnior César Da Silva","contato@jsilvaleiloes.com.br","JUCEAC"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCEAC"),
    ("Mariana Gouvea Lessa","marianagouvea@hotmail.com","JUCEAC"),
    ("Patricia Pimentel Grocoski Costa","patricia@pimentelleiloes.com.br","JUCEAC"),
    ("Sandro De Oliveira","olsandro@yahoo.com.br","JUCEAC"),
    ("Thaís Costa Bastos Teixeira","thais@thaisteixeiraleiloes.com.br","JUCEAC"),
    ("Tiago Tessler Blecher","tiago.tessler@webleiloes.com.br","JUCEAC"),
    ("Valdyr Alves De Sá","valdyrsa@gmail.com","JUCEAC"),
    ("Vera Lúcia Aguiar De Sousa","sousa.veralucia@hotmail.com","JUCEAC"),
    ("Vera Maria Aguiar De Sousa","sousa.veramaria@hotmail.com","JUCEAC"),
    ("Vladmir Oliani","vladmiroliani@hotmail.com","JUCEAC"),
    ("Wesley Silva Ramos","wesleyleiloeiro@gmail.com","JUCEAC"),
    # ── JUCEB ─────────────────────────────────────────────────────────────────
    ("Alberto José Marchi Macedo","alberto@albertomacedoleiloes.com.br","JUCEB"),
    ("Alessandra Cristine Aparecida De Carlos","contato@alessandraleiloes.com.br","JUCEB"),
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCEB"),
    ("Anderson Douglas Gali Falleiros","contato@falleirosleiloes.com.br","JUCEB"),
    ("Angela Saraiva Portes Souza","angela@saraivaleiloes.com.br","JUCEB"),
    ("Anna Karoline Santos do Amaral","akarolineamaral@gmail.com","JUCEB"),
    ("Antonio Luiz Guariglia","antonio@guariglialeiloes.com.br","JUCEB"),
    ("AntÃ´nio Romero Ferreira Da Silva","romerosilva@leiloescostaesilva.com.br","JUCEB"),
    ("Arthur Ferreira Nunes","arthur@nordesteleiloes.com.br","JUCEB"),
    ("Catiele Borges Leffa","leffa@leffaleiloes.com.br","JUCEB"),
    ("Celso Alves Cunha","celsocunhaleiloes@gmail.com","JUCEB"),
    ("Clauberto Fernandes Nascimento Júnior","hatoryleiloes@hotmail.com","JUCEB"),
    ("Cristiane Borguetti Moraes Lopes","atendimento@lopesleiloes.com.br","JUCEB"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEB"),
    ("Daniel Melo Cruz","priscilla@grupolance.com.br","JUCEB"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com","JUCEB"),
    ("Dora Plat","dplat@portalzuk.com.br","JUCEB"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCEB"),
    ("Erick Soares Teles","erick@positivoleiloes.com.br","JUCEB"),
    ("Fabio Da Silva Ferreira","fabio@lamurleiloes.com.br","JUCEB"),
    ("Fábio Manoel Guimarães","contato@fabioleiloes.com.br","JUCEB"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCEB"),
    ("Fernando José Cerello Gonçalves Pereira","fernando@megaleiloes.com.br","JUCEB"),
    ("Gustavo Moretto G. de Oliveira","contato@gustavomorettoleiloeiro.com.br","JUCEB"),
    ("Irani Flores","joao.victor@leilaobrasilveiculos.com.br","JUCEB"),
    ("José David Gonçalves De Melo","jose@jdleiloes.com.br","JUCEB"),
    ("Josecelli Kildare Fraga Gomes","kildare.gomes@hotmail.com","JUCEB"),
    ("Jussiara Santos Ermano Sukiennik","contato@jussiaraleiloes.com","JUCEB"),
    ("Kátia Cerqueira Da Silva Casaes","contato@kcleiloes.com.br","JUCEB"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@yahoo.com.br","JUCEB"),
    ("Marco Túlio Montenegro Cavalcanti Dias","marcotulio@lancecertoleiloes.com.br","JUCEB"),
    ("Marcus Vinicius Yoshimi Uebara","licitacao@destakleiloes.com.br","JUCEB"),
    ("Maria Isabel Brito Mendes Palma Soeiro","isabel@isabelleiloes.com.br","JUCEB"),
    ("Maurice Da Silva Oliveira","atendimento@msoleiloes.com.br","JUCEB"),
    ("Maurício Paes Inácio","contato@hastaleiloes.com.br","JUCEB"),
    ("Miguel Paulo Rodrigues Da Silva","mpleiloes@mpleiloes.com.br","JUCEB"),
    ("Rafaela Melo Ferreira Marzano","marinacoelho@palaciodosleiloes.com.br","JUCEB"),
    ("Renan Souza Silva","renan@silvaleiloes.com.br","JUCEB"),
    ("Rodrigo Schmitz","contato@hleiloes.com","JUCEB"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCEB"),
    ("Simone De Queiroz","simoneq.leiloes@gmail.com","JUCEB"),
    ("Tiago Tessler Blecher","credenciamento@webleiloes.com.br","JUCEB"),
    ("Viriato Domingues Cravo","contato@cravoleiloes.com.br","JUCEB"),
    # ── JUCEES ────────────────────────────────────────────────────────────────
    ("Alessandro De Assis Teixeira","contato@alessandroteixeiraleiloes.com.br","JUCEES"),
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCEES"),
    ("Alexandre Buaiz Neto","atendimento.documentacao@buaizleiloes.com.br","JUCEES"),
    ("Alexsander Pretti Domingos","alexsanderpretti@hotmail.com","JUCEES"),
    ("Ayrton De Souza Porto Filho","ayrtonporto@gmail.com","JUCEES"),
    ("Brenno De Figueiredo Porto","brenno@portoleiloes.com.br","JUCEES"),
    ("Bruno Birschner Lube","lube.bruno@hotmail.com","JUCEES"),
    ("Caio De Carvalho Borges","cb.leiloeiro@gmail.com","JUCEES"),
    ("Carla Karine Santos Agostinho","carlaleiloeira@gmail.com","JUCEES"),
    ("Caroline De Sousa Ribas","caroline@liderleiloes.com.br","JUCEES"),
    ("Dalton Luis De Moraes Leal","paivaleiloeiro@uol.com.br","JUCEES"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEES"),
    ("Daniel Melo Cruz","priscilla@grupolance.com.br","JUCEES"),
    ("Davi Borges De Aquino","inscricoes@alfaleiloes.com","JUCEES"),
    ("Dora Plat","dplat@portalzuk.com.br","JUCEES"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCEES"),
    ("Erick Soares Teles","teles@teza.com.br","JUCEES"),
    ("EstevÃ£o Strini Camilo","estevaocamilo@hotmail.com","JUCEES"),
    ("Fernando Caetano Moreira Filho","fernandoleiloeiro@yahoo.com.br","JUCEES"),
    ("Flávia De Oliveira Rocha","mcr@leilofacil.lel.br","JUCEES"),
    ("Gabriel Fardin Pereira","gabrielleiloes@gmail.com","JUCEES"),
    ("Gustavo Bolzan","gustavo@gbleiloes.com.br","JUCEES"),
    ("Gustavo Martins Rocha","grleiloes@grleiloes.com","JUCEES"),
    ("Gustavo Moretto G. de Oliveira","contato@gustavomorettoleiloeiro.com.br","JUCEES"),
    ("Hidirlene Duszeiko","hidirlene@hdleiloes.com.br","JUCEES"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEES"),
    ("Jonas Rymer","rymerleiloes@gmail.com","JUCEES"),
    ("José Sérgio Della Giustina","jgiustina@hotmail.com","JUCEES"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@yahoo.com.br","JUCEES"),
    ("Luiz Roberto de Oliveira Brenneken","luiz.brenneken@gmail.com","JUCEES"),
    ("Marco Antonio B. De O. Junior","juridico@marcoantonioleiloeiro.com.br","JUCEES"),
    ("Marcos Rodrigo C. Soares","sac@custodioleiloes.com.br","JUCEES"),
    ("Mauro Colodete","sac@colodeteleiloes.com.br","JUCEES"),
    ("Orlando Lopes Fernandes","lopes.fernandes@uol.com.br","JUCEES"),
    ("Paulo Cesar Agostinho","agostinho@agostinholeiloes.com.br","JUCEES"),
    ("Pietrangelo Rosalem","pietrangelorosalem@gmail.com","JUCEES"),
    ("Renan Neris Da Silva","renan290592@gmail.com","JUCEES"),
    ("Renato Schlobach Moyses","renato.moyses@majudicial.com.br","JUCEES"),
    ("Ronald De Freitas Moreira","ronaldfmoreira@gmail.com","JUCEES"),
    ("Ruam Carlos Chaves Gotardo","contato@serranaleiloes.com.br","JUCEES"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCEES"),
    ("Sandra De Fátima Santos","sandrafsantosleiloeira@gmail.com","JUCEES"),
    ("Sued Peter Bastos Dyna","leiloeiro@suedpeterleiloes.com.br","JUCEES"),
    ("Thiago Tessler Blecher","credenciamento@webleiloes.com.br","JUCEES"),
    # ── JUCEMAT ───────────────────────────────────────────────────────────────
    ("Abiel Ismael Duarte dos Santos","contato@manaleiloes.com.br","JUCEMAT"),
    ("Alan Carlos dos Santos","contato@matogrossoleiloes.com.br","JUCEMAT"),
    ("Alberto José Marchi Macedo","alberto@albertomacedoleiloes.com.br","JUCEMAT"),
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCEMAT"),
    ("AlgLécio Bueno da Silva","contato@leiloesgoias.com.br","JUCEMAT"),
    ("Ana Paula Pincegher Brasil","anapaula@paulobrasil.com.br","JUCEMAT"),
    ("Antonio José da Silva Filho","suporte@ajleiloes.com.br","JUCEMAT"),
    ("Aparecida Maria Fixer","cida@fixerleiloes.com.br","JUCEMAT"),
    ("Brian Galvão Frota","brian@gfleiloes.com.br","JUCEMAT"),
    ("Carlos Henrique Barbosa","contato@chbarbosaleiloes.com.br","JUCEMAT"),
    ("Cirlei Freitas Balbino Da Silva","contato@balbinoleiloes.com.br","JUCEMAT"),
    ("Cleber Cardoso Pereira","cleber@clebercardosoleiloes.com.br","JUCEMAT"),
    ("Conceição Maria Fixer","contato@mariafixerleiloes.com.br","JUCEMAT"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEMAT"),
    ("Daniel Melo Cruz","contato@grupolance.com.br","JUCEMAT"),
    ("Daniel Oliveira Junior","daniel@danieloliveiraleiloes.com.br","JUCEMAT"),
    ("Davi Borges De Aquino","inscricoes@alfaleiloes.com","JUCEMAT"),
    ("Denys Pyerre De Oliveira","contato@leje.com.br","JUCEMAT"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCEMAT"),
    ("Elton Luiz Simon","elton@simonleiloes.com.br","JUCEMAT"),
    ("Erick Soares Teles","erick@positivoleiloes.com.br","JUCEMAT"),
    ("Fabio Gonçalves Barbosa","fabio@fabiobarbosaleiloes.com.br","JUCEMAT"),
    ("Fabio Prando Fagundes Góes","fabio.goes@apiceleiloes.com","JUCEMAT"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCEMAT"),
    ("Fernando José Cerello Gonçalves Pereira","fernando@megaleiloes.com.br","JUCEMAT"),
    ("Franciele Aparecida da Silva","contato@dasilvaleiloes.com.br","JUCEMAT"),
    ("Gustavo de Moretto Guimarães de Oliveira","contato@gustavomorettoleiloeiro.com.br","JUCEMAT"),
    ("Icaro Alexandre Felfili Jardim","icaroleiloes@hotmail.com","JUCEMAT"),
    ("Irani Flores","irani.flores@leilaobrasil.com.br","JUCEMAT"),
    ("Joabe Balbino Da Silva","joabe@balbinoleiloes.com.br","JUCEMAT"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEMAT"),
    ("Katiuscia Martins Araujo","katiuscia_araujo@hotmail.com","JUCEMAT"),
    ("Leonardo Coelho Avelar","arrematabem@arrematabem.com.br","JUCEMAT"),
    ("LoemÃ­ Gonçalves Santana","atendimento@globoleiloes.com.br","JUCEMAT"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCEMAT"),
    ("Luiz Balbino da Silva","balbino@balbinoleiloes.com.br","JUCEMAT"),
    ("Marciano Aguiar Carneiro","marcianoleiloes@gmail.com","JUCEMAT"),
    ("Mariangela Bellissimo Uebara","contato@destakleiloes.com.br","JUCEMAT"),
    ("Mike Dutra Fleitas","mikedutraleiloeiro@gmail.com","JUCEMAT"),
    ("Mouzar Baston Filho","mouzar@bastonleiloes.com.br","JUCEMAT"),
    ("Rafael Cicolin","contato@imperioleiloes.com","JUCEMAT"),
    ("Raphael Perini de Souza","contato@pantanalleiloesjudiciais.com.br","JUCEMAT"),
    ("Rodrigo Schmitz","contato@hleiloes.com","JUCEMAT"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCEMAT"),
    ("Sergio Fleury Batista","sergio@portalleilomaster.com.br","JUCEMAT"),
    ("Tiago Tessler Blecher","tiago.tessler@webleiloes.com.br","JUCEMAT"),
    ("Victor Alberto Severino Frazão","victor@sfrazao.com.br","JUCEMAT"),
    # ── JUCEMG ────────────────────────────────────────────────────────────────
    ("Adriana Pires Amancio","adriana.pires@apaleiloes.com.br","JUCEMG"),
    ("Adriano Apolinário Leão De Oliveira","contato@adrianoleiloeiro.com.br","JUCEMG"),
    ("Alessandro De Assis Teixeira","contato@alessandroteixeiraleiloes.com.br","JUCEMG"),
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCEMG"),
    ("Alexandra Benedita De Sousa Casado","contato@ecoleiloes.com.br","JUCEMG"),
    ("Angela Saraiva Portes Souza","angela@saraivaleiloes.com.br","JUCEMG"),
    ("Antonio Luiz Guariglia","antonio@guariglialeiloes.com.br","JUCEMG"),
    ("Arnaldo Emílio Colombarolli","arnaldoleiloes@gmail.com","JUCEMG"),
    ("Breno Augusto Magalhães Da Anunciação","contato@bmleiloes.com.br","JUCEMG"),
    ("Breno César Oliveira Farias","breno.cesar@brfleiloes.com.br","JUCEMG"),
    ("Carla Karine Santos Agostinho","carlaleiloeira@gmail.com","JUCEMG"),
    ("CARLOS CHUI","contato@arremataronline.com.br","JUCEMG"),
    ("Carolina Camargos Marques Florentino","carolinacamargos@hotmail.com","JUCEMG"),
    ("Caroline De Sousa Ribas","caroline@liderleiloes.com.br","JUCEMG"),
    ("Catiele Borges Leffa","leffa@leffaleiloes.com.br","JUCEMG"),
    ("Cleber Cardoso Pereira","cleber@clebercardosoleiloes.com.br","JUCEMG"),
    ("ClÃ©cio Oliveira de Carvalho","clecio@leilaooficialonline.com.br","JUCEMG"),
    ("Cristiane Borguetti Moraes Lopes","cristiane@lopesleiloes.com.br","JUCEMG"),
    ("Cristiano Gomes Ferreira","crisferreira0411@gmail.com","JUCEMG"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEMG"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com","JUCEMG"),
    ("Denys Pyerre De Oliveira","contato@leje.com.br","JUCEMG"),
    ("DÃ­lson Marcos Moreira","dilson.moreira@dilsonleiloeiro.com","JUCEMG"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCEMG"),
    ("Everton Dias Medeiros","contato@diasleiloes.com.br","JUCEMG"),
    ("Fábio Manoel Guimarães","contato@fabioleiloes.com.br","JUCEMG"),
    ("Fernanda De Mello Franco","fernanda@francoleiloes.com.br","JUCEMG"),
    ("Fernando Caetano Moreira Filho","fernandoleiloeiro@yahoo.com.br","JUCEMG"),
    ("Fernando Chui","fernando@chuileiloes.com.br","JUCEMG"),
    ("Fernando José Cerello Gonçalves Pereira","fernando@megaleiloes.com.br","JUCEMG"),
    ("Flávia Figueira Messias","contato@messiasleiloes.com.br","JUCEMG"),
    ("Flávio Duarte Ceruli","leiloes@leiloesceruli.com.br","JUCEMG"),
    ("Giselle Fernanda Stefanelli Campos Souza","leiloes@leiloestefanelli.com.br","JUCEMG"),
    ("Guilherme Caixeta Borges","guilherme@milhaoleiloes.com.br","JUCEMG"),
    ("GUSTAVO MORETTO GUIMARÃES DE OLIVEIRA","contato@gustavomorettoleiloeiro.com.br","JUCEMG"),
    ("Gustavo Costa Aguiar Oliveira","gustavo@gpleiloes.com.br","JUCEMG"),
    ("HELCIO KRONBERG","helcio@kronbergleiloes.com.br","JUCEMG"),
    ("Heliana Maria Oliveira Melo Ferreira","helianaferreira@palaciodosleiloes.com.br","JUCEMG"),
    ("Irani Flores","irani.flores@leilaobrasil.com.br","JUCEMG"),
    ("Isaías Rosa Ramos Júnior","leiloes@isaiasleiloes.com.br","JUCEMG"),
    ("Izabella Melo Ferreira Praes","izabellaferreira@palaciodosleiloes.com.br","JUCEMG"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEMG"),
    ("José António Rodovalho Júnior","contato@leiloesjudiciaismgnorte.com.br","JUCEMG"),
    ("José Luiz Pereira Vizeu","joseluiz@flexleiloes.com.br","JUCEMG"),
    ("José Valero Santos Junior","contato@valeroleiloes.com.br","JUCEMG"),
    ("Kananda Sofia Silva Macedo","admin@kanandaleiloes.com.br","JUCEMG"),
    ("Lucas de Oliveira Mangualde","leiloeirolucas@gmail.com","JUCEMG"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@yahoo.com.br","JUCEMG"),
    ("Luiz Felipe Perpétuo Lobato","contato@openleiloes.com.br","JUCEMG"),
    ("Luiz Fernando Frange Abrahão","luizfrange@hotmail.com","JUCEMG"),
    ("Magnun Luiz Serpa","contato@serpaleiloes.com.br","JUCEMG"),
    ("Marco António Barbosa De Oliveira Junior","contato@marcoantonioleiloeiro.com.br","JUCEMG"),
    ("Marcos Roberto Torres","leiloeiro@3torresleiloes.com.br","JUCEMG"),
    ("Marcos Rodrigo CustÓdio Soares","marcoscustodioadv@hotmail.com","JUCEMG"),
    ("Marcus Vinicius Yoshimi Uebara","contato@destakleiloes.com.br","JUCEMG"),
    ("MAURICIO SAMBUGARI APPOLINARIO","contato@selectleiloes.com.br","JUCEMG"),
    ("Mouzar Baston Filho","mouzar@bastonleiloes.com.br","JUCEMG"),
    ("Orlando Araujo Dos Santos","contato@oaleiloes.com.br","JUCEMG"),
    ("Paulo César Agostinho","contato@agostinholeiloes.com.br","JUCEMG"),
    ("Gilherme LuizPeles","contato@pelesleiloeiro.com.br","JUCEMG"),
    ("Pedro Miranda Jinkings","contato@milhaoleiloes.com.br","JUCEMG"),
    ("Pietrangelo Rosalem","pietrangelorosalem@gmail.com","JUCEMG"),
    ("Priscilla Lopes Ribeiro Ferreira","priscilla@ferreiraleiloes.com.br","JUCEMG"),
    ("Rafael Araújo Gomes","rafaelleiloeiro@gmail.com","JUCEMG"),
    ("Rafaela Melo Ferreira Marzano","rafaelaferreira@palaciodosleiloes.com.br","JUCEMG"),
    ("Renata Fátima Veloso","contato@rvleiloes.com.br","JUCEMG"),
    ("Renato Guedes Rocha","contato@rioleiloes.com.br","JUCEMG"),
    ("Rodrigo Aparecido Rigolon da Silva","contato@rigolonleiloes.com.br","JUCEMG"),
    ("Rodrigo De Oliveira Lopes","rodrigo@leiloesuberlandia.com.br","JUCEMG"),
    ("Rodrigo Schmitz","hleiloes@hleiloes.com","JUCEMG"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCEMG"),
    ("Sandra De Fátima Santos","sandrafsantosleiloeira@gmail.com","JUCEMG"),
    ("Suellen Soares Ribeiro","contato@ssleiloes.com","JUCEMG"),
    ("Tatiana Paula Zani De Sousa","tatianasousa@liderleiloes.com.br","JUCEMG"),
    ("Thaís Costa Bastos Teixeira","thais@leiloesjudiciais.com.br","JUCEMG"),
    ("Thais Silva Moreira De Sousa","thais@tmleiloes.com.br","JUCEMG"),
    ("Thiago Luis Stefanelli Campos","thiago@stefanellileiloes.com.br","JUCEMG"),
    ("ULISSES DONIZETE RAMOS","leiloeiro@donizetteleiloes.com.br","JUCEMG"),
    ("Viviane Garzon Corrêa","viviane@bolsadeleiloes.com.br","JUCEMG"),
    ("Joel Augusto Picelli Filho","joel@picellileiloes.com.br","JUCEMG"),
    # ── JUCEMS ────────────────────────────────────────────────────────────────
    ("Ana Claudia Blasczyk","anaclaudia@leiloesjudiciais.com.br","JUCEMS"),
    ("Aparecida Maria Fixer","cidafixer@leiloesjudiciais.com.br","JUCEMS"),
    ("Arthur Ferreira Nunes","atendimento@arthurnunesleiloes.com.br","JUCEMS"),
    ("Bruno Barreto Sanches","bruno@barretoleiloes.com.br","JUCEMS"),
    ("Camila Correia Vecchi Aguiar","vecchileiloes@gmail.com","JUCEMS"),
    ("Cassia Negrete Nunes Balbino","cassiabalbino@globoleiloes.com.br","JUCEMS"),
    ("Catiele Borges Leffa","leffa@leffaleiloes.com.br","JUCEMS"),
    ("Cecilia Delzeir Sobrinho","atendimento@ceciliadelzeirleiloes.com.br","JUCEMS"),
    ("Cibele Rigolin Pereira De Figueiredo","contato@ipcleiloes.com.br","JUCEMS"),
    ("Conceição Maria Fixer","contato@mariafixerleiloes.com.br","JUCEMS"),
    ("Cristiane Borguetti Moraes Lopes","atendimento@lanceja.com.br","JUCEMS"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEMS"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com","JUCEMS"),
    ("Denys Pyerre De Oliveira","contato@leje.com.br","JUCEMS"),
    ("Dora Plat","contato@portalzuk.com.br","JUCEMS"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCEMS"),
    ("Elton Luiz Simon","elton@simonleiloes.com.br","JUCEMS"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCEMS"),
    ("Fernando Jose Cerello Gonçalves Pereira","fernando@megaleiloes.com.br","JUCEMS"),
    ("Gustavo Correa Pereira Da Silva","gustavocorrealeiloeiro@gmail.com","JUCEMS"),
    ("Helder Pereira De Figueiredo Junior","helderjr@ipcleiloes.com.br","JUCEMS"),
    ("Igor Alexandre De Souza Silva","desouza@desouzaleiloes.com.br","JUCEMS"),
    ("Irani Flores","irani.flores@leilaobrasil.com.br","JUCEMS"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEMS"),
    ("Jonas Rymer","jonasrymer@gmail.com","JUCEMS"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@yahoo.com.br","JUCEMS"),
    ("Marcelo Carneiro Bernardelli","marcelo@marcaleiloes.com.br","JUCEMS"),
    ("Maridulce Sanfelice Simei","contato@msleiloes.com","JUCEMS"),
    ("MAURICIO SAMBUGARI APPOLINARIO","contato@selectleiloes.com.br","JUCEMS"),
    ("Milena Rosa Di Giacomo Adri Faverão","contatoms@megaleiloes.com.br","JUCEMS"),
    ("Mouzar Baston Filho","mouzar@bastonleiloes.com.br","JUCEMS"),
    ("Patricia Pimentel Grocoski Costa","contato@pimentelleiloes.com.br","JUCEMS"),
    ("Reinaldo Rodrigues Perdomo","reinaldo@casadeleiloes.com.br","JUCEMS"),
    ("Rodrigo Aparecido Rigolon da Silva","contato@rigolonleiloes.com.br","JUCEMS"),
    ("Rodrigo Schmitz","contato@hleiloes.com","JUCEMS"),
    ("Tarcilio Leite","tarcilioleite@casadeleiloes.com.br","JUCEMS"),
    ("Tiago Tessler Blecher","tiago.tessler@webleiloes.com.br","JUCEMS"),
    ("Wesley Oliveira Ascanio","wesley@tabaleiloes.com.br","JUCEMS"),
    # ── JUCEPAR ───────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCEPAR"),
    ("ADRIANO MELNISKI","contato@amleiloeiro.com.br","JUCEPAR"),
    ("ANTONIO MAGNO JACOB DA ROCHA","juridico@rochaleiloes.com.br","JUCEPAR"),
    ("Catiele Borges Leffa","leffa@leffaleiloes.com.br","JUCEPAR"),
    ("CLEVER ELMES MILANI","contato@milanileiloes.com.br","JUCEPAR"),
    ("CLAUDIO CESAR KUSS","claudio@claudiokussleiloes.com.br","JUCEPAR"),
    ("Cristiane Borguetti Moraes Lopes","atendimento@lopesleiloes.com.br","JUCEPAR"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEPAR"),
    ("Davi Borges De Aquino","inscricoes@alfaleiloes.com","JUCEPAR"),
    ("ELTON LUIZ SIMON","elton@simonleiloes.com.br","JUCEPAR"),
    ("Erick Soares Teles","teles@tezaleiloes.com.br","JUCEPAR"),
    ("EUCLIDES MARASCHI JUNIOR","marascajr@hastapublica.com.br","JUCEPAR"),
    ("FABIO GONCALVES BARBOSA","contato@fabiobarbosaleiloes.com.br","JUCEPAR"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCEPAR"),
    ("FERNANDO DE OLIVEIRA KUSS","contato@ksleiloes.com.br","JUCEPAR"),
    ("GUILHERME EDUARDO STUTZ TOPOROSKI","contato@topoleiloes.com.br","JUCEPAR"),
    ("GUSTAVO MORETTO GUIMARÃES DE OLIVEIRA","contato@gustavomorettoleiloeiro.com.br","JUCEPAR"),
    ("HELCIO KRONBERG","contato@kronbergleiloes.com.br","JUCEPAR"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCEPAR"),
    ("JOAO LUIZ DE OLIVEIRA","joaoluiz@joaoluizleiloes.com.br","JUCEPAR"),
    ("Josecelli Kildare Fraga Gomes","kildare.gomes@hotmail.com","JUCEPAR"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCEPAR"),
    ("LUIZ BARBOSA DE LIMA JUNIOR","contato@lbleiloes.com.br","JUCEPAR"),
    ("LUIZ ODAIR FAVARETO","favareto@favaretoleiloes.com.br","JUCEPAR"),
    ("MARCELO SOARES DE OLIVEIRA","marcelo@oleiloes.com.br","JUCEPAR"),
    ("Marcus Vinicius Yoshimi Uebara","licitacao@destakleiloes.com.br","JUCEPAR"),
    ("Marilaine Borges De Paula","leiloeiro@e-confianca.com.br","JUCEPAR"),
    ("MAURICIO SAMBUGARI APPOLINARIO","andraleiloes@andraleiloes.com.br","JUCEPAR"),
    ("PATRICIA GRAZIELA DE MELO BARCELLOS","patricia@barcellos.lel.br","JUCEPAR"),
    ("Patricia Pimentel Grocoski Costa","contato@pimentelleiloes.com.br","JUCEPAR"),
    ("Paulo Alexandre Heisler","pauloalexandreheisler@gmail.com","JUCEPAR"),
    ("PAULO ROBERTO NAKAKOGUE","paulo@nakakogueleiloes.com.br","JUCEPAR"),
    ("Renan Souza Silva","contato@silvaleiloes.com.br","JUCEPAR"),
    ("Renato Schlobach Moyses","intimacao@rmoyses.com.br","JUCEPAR"),
    ("Rodrigo Aparecido Rigolon da Silva","contato@rigolonleiloes.com.br","JUCEPAR"),
    ("Rodrigo Schmitz","contato@hleiloes.com","JUCEPAR"),
    ("RUBENS HENRIQUE DE CASTRO","rhc.leiloes@gmail.com","JUCEPAR"),
    ("RUDIVAL ALMEIDA GOMES JUNIOR","rudival@rjleiloes.com.br","JUCEPAR"),
    ("Sidney Belarmino Ferreira Junior","atendimento@sfleiloes.com.br","JUCEPAR"),
    ("SPENCER D'AVILA FOGAGNOLI","spencer@spencerleiloes.com.br","JUCEPAR"),
    ("Tatiana Paula Zani De Sousa","tatianasousa@liderleiloes.com.br","JUCEPAR"),
    ("Tiago Tessler Blecher","tiago.tessler@webleiloes.com.br","JUCEPAR"),
    ("ULISSES DONIZETE RAMOS","leiloeiro@donizetteleiloes.com.br","JUCEPAR"),
    ("WERNO KLÖCKNER JÚNIOR","werno@kleiloes.com.br","JUCEPAR"),
    # ── JUCEPE ────────────────────────────────────────────────────────────────
    ("Adriano Santos Venceslau Da Silva","fatima@coliseumleiloes.com.br","JUCEPE"),
    ("Alexandre Ferreira Nunes","leiloeiro@gmail.com","JUCEPE"),
    ("Antonio Albino Queiroz Ferreira","albino@albinoqueiroz.com.br","JUCEPE"),
    ("Carlos Cavalcanti De Albuquerque Ramos","carlos@liderancaleiloes.com.br","JUCEPE"),
    ("Cassiano Ricardo Dall'Ago E Silva","cassiano@cassianoleiloes.com.br","JUCEPE"),
    ("Cesar Britto Martins","contato@brittoleiloes.com.br","JUCEPE"),
    ("Denys Pyerre De Oliveira","dpyerre@yahoo.com.br","JUCEPE"),
    ("Diogo Mattos Dias Martins","diogo@inovaleilao.com.br","JUCEPE"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCEPE"),
    ("Gustavo Henrique Valença De Melo","gustavo.melo@ghvmleiloes.com.br","JUCEPE"),
    ("José António Montenegro Maia","josemaia@leiloesmaia.com.br","JUCEPE"),
    ("JosuÃ© Sérgio De Oliveira Júnior","j.sergiooliveira@hotmail.com","JUCEPE"),
    ("Luciano Resende Rodrigues","luciano@lancecertoleiloes.com.br","JUCEPE"),
    ("Osman Sobral E Silva","osman@leiloesfreire.com.br","JUCEPE"),
    ("Rui De Almeida Pereira","ruileiloeiro@gmail.com","JUCEPE"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCEPE"),
    # ── JUCEPI ────────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","licitacoes@hoppeleiloes.com.br","JUCEPI"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCEPI"),
    ("Erico Sobral Soares","erico.sobral@vipleiloes.com.br","JUCEPI"),
    ("Fernando Caetano Moreira Filho","fernandoleiloeiro@yahoo.com.br","JUCEPI"),
    ("Italo Trindade Moura","italo@italoleiloes.com","JUCEPI"),
    ("José David Gonçalves De Melo","contato@jdleiloes.com.br","JUCEPI"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCEPI"),
    ("Maurício José De Sousa Costa","contato@mjleiloes.com.br","JUCEPI"),
    ("Rodrigo Aparecido Rigolon da Silva","contato@rigolonleiloes.com.br","JUCEPI"),
    ("Sergio Roberto Nogueira Lima","sergiorobertonogueira@gmail.com","JUCEPI"),
    ("Suzana Conceição Medeiros De Carvalho","suzanacarvalholeiloes@hotmail.com","JUCEPI"),
    # ── JUCER ─────────────────────────────────────────────────────────────────
    ("Ana Carolina Zaninetti Rosa","leiloes.rondonia@gmail.com","JUCER"),
    ("Bruno Pimentel Rosa","contato@lancevip.com.br","JUCER"),
    ("Carlos Henrique Barbosa","contato@chbarbosaleiloes.com.br","JUCER"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCER"),
    ("Deonizia Kiratch","contato@deonizialeiloes.com.br","JUCER"),
    ("Evanilde Aquino Pimentel Rosa","contato@lancevip.com.br","JUCER"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCER"),
    ("Flavia Correa Duarte Feitosa","flavia.duarte.leiloeira@gmail.com","JUCER"),
    ("Francisco Portela Aguiar","portela.ro@hotmail.com","JUCER"),
    ("Joabe Balbino Da Silva","joabeleiloeiro@globoleiloes.com.br","JUCER"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCER"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCER"),
    ("Marcus Allain De Oliveira Barbosa","maleiloesro@hotmail.com","JUCER"),
    ("Marcus Vinicius Moreira Chaves","viniciusleiloesro@hotmail.com","JUCER"),
    ("Patricia Pimentel Grocoski Costa","patricia@pimentelleiloes.com.br","JUCER"),
    ("ThaÃ­s Costa Bastos Teixeira","contato@thaisteixeiraleiloes.com.br","JUCER"),
    ("Vera Lúcia Aguiar De Sousa","sousa.veralucia@hotmail.com","JUCER"),
    # ── JUCERJA ───────────────────────────────────────────────────────────────
    ("Alan Machado Ribeiro","alan@alanleiloeiro.com.br","JUCERJA"),
    ("Alexandre Pereira Da Costa","alexandre@alexandrecostaleiloes.com.br","JUCERJA"),
    ("Alexandro Da Silva Lacerda","contato@alexandroleiloeiro.com.br","JUCERJA"),
    ("Ana Lucia Gomes De Sá","contato@analucialeiloeira.com.br","JUCERJA"),
    ("Antonio Claudio Brites","contato@britesleiloeiro.com.br","JUCERJA"),
    ("Antonio Carlos Da Costa Ferreira","leiloeiro@antonioferreira.lel.br","JUCERJA"),
    ("Bianca Soares Pais De Carvalho","biancapais@bspleiloes.com.br","JUCERJA"),
    ("Cristina Façanha","contato@facanhaleiloes.com.br","JUCERJA"),
    ("Daniele De Lima De Paula","depaula@depaulaonline.com.br","JUCERJA"),
    ("Danielle Haddad","rosa.medeiros@robertohaddad.com.br","JUCERJA"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCERJA"),
    ("Dora Plat","dplat@portalzuk.com.br","JUCERJA"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCERJA"),
    ("Fabiano Ayupp Magalhães","contato@fabianoleiloeiro.net","JUCERJA"),
    ("Fabiola Porto Portella","leiloes@portellaleiloes.com.br","JUCERJA"),
    ("Fábio Manoel Guimarães","f.guimaraes@leiloesjudiciais.com.br","JUCERJA"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCERJA"),
    ("Fernando Moreira Braga","fb@fernandobraga.lel.br","JUCERJA"),
    ("GIORDANO BRUNO COAN AMADOR","contato@giordanoleiloes.com.br","JUCERJA"),
    ("Gustavo Moretto Guimaraes De Oliveira","contato@gustavomorettoleiloeiro.com.br","JUCERJA"),
    ("Gustavo Portella Lourenço","gustavoleiloes@hotmail.com","JUCERJA"),
    ("Irani Flores","juridico02@palaciodosleiloes.com.br","JUCERJA"),
    ("Jean Fellipe Mattos Tavares","tavaresleiloes@gmail.com","JUCERJA"),
    ("Jessualdo Fortuna Le Gentil","contato@leiloeirolegentil.com.br","JUCERJA"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCERJA"),
    ("Jonas Rymer","joseantonioadvogado@yahoo.com.br","JUCERJA"),
    ("Josimar De Azevedo Santos","josimar@josimarleiloeiro.com.br","JUCERJA"),
    ("Leandro Dias Brame","leandro@brameleiloes.com.br","JUCERJA"),
    ("Leonardo Schulmann","schulmann@schulmann.com.br","JUCERJA"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@yahoo.com.br","JUCERJA"),
    ("Luiz Tenório De Paula","depaula@depaulaonline.com.br","JUCERJA"),
    ("Marcus Vinicius Yoshimi Uebara","contato@destakleiloes.com.br","JUCERJA"),
    ("Mauricio Kronemberg Hartmann","contato@mauriciokronemberg.com.br","JUCERJA"),
    ("Murilo Cardozo Chaves","leilao@murilochaves.com.br","JUCERJA"),
    ("Raul Barbosa Cesar Filho","raulbarbosa@raulbarbosa.lel.br","JUCERJA"),
    ("Renato Guedes Rocha","contato@rioleiloes.com.br","JUCERJA"),
    ("Roberto Haddad","rosa.medeiros@robertohaddad.com.br","JUCERJA"),
    ("Rodrigo Da Conceição Prata","contato@cariocaleiloes.com.br","JUCERJA"),
    ("Rodrigo Da Silva Costa","leiloeiro@rodrigocostaleiloeiro.com.br","JUCERJA"),
    ("Rodrigo Lopes Portella","rodrigo@portellaleiloes.com.br","JUCERJA"),
    ("Rogério Menezes Nunes","andre@rogeriomenezes.com.br","JUCERJA"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCERJA"),
    ("Severino Barbosa","sbleiloeiro@gmail.com","JUCERJA"),
    ("Silas Barbosa Pereira","silasleiloeiro@globo.com","JUCERJA"),
    # ── JUCERN ────────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCERN"),
    ("AntÃ´nio Romero Ferreira Da Silva","romerosilva@leiloescostaesilva.com.br","JUCERN"),
    ("Celso Alves Cunha","celsocunhaleiloes@gmail.com","JUCERN"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCERN"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com","JUCERN"),
    ("Davi Eduardo Paulim","davipaulim@gmail.com","JUCERN"),
    ("Edeylson Peixoto Fidelis","fidelis@fidelisleiloes.com.br","JUCERN"),
    ("Erick Luiz Neves Da Câmara","erickcamara_leiloeirooficial@yahoo.com.br","JUCERN"),
    ("Filipe Pedro De Araújo","filipe_leiloeiro@hotmail.com","JUCERN"),
    ("Francisco Doege Esteves Filho","francisco.doege@gmail.com","JUCERN"),
    ("Jussara Medeiros","jussaraleiloeira@gmail.com","JUCERN"),
    ("Luciano De Morais Rabelo Soares","lsprm@live.com","JUCERN"),
    ("Marcus Dantas Nepomuceno","marcusnepomuceno@mnleilao.com.br","JUCERN"),
    ("Renato Schlobach Moyses","renato.moyses@rmoyses.com.br","JUCERN"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCERN"),
    # ── JUCERR ────────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCERR"),
    ("BRIAN GALVÃO FROTA","brian@amazonasleiloes.com.br","JUCERR"),
    ("Carlos Henrique Barbosa","contato@chbarbosaleiloes.com.br","JUCERR"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCERR"),
    ("Deonizia Kiratch","contato@deonizialeiloes.com.br","JUCERR"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCERR"),
    ("Flavia Correa Duarte Feitosa","flavia.duarte.leiloeira@gmail.com","JUCERR"),
    ("HUGO MOREIRA PIMENTA","hugo@moreirapimenta.lel.br","JUCERR"),
    ("JIMMY ASAMI","jimmy@asamileiloes.com.br","JUCERR"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com","JUCERR"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCERR"),
    ("MARIANA GOVÊA LESSA","mariana.lessa@vipleiloes.com.br","JUCERR"),
    ("MAYCO SILVA DOS SANTOS","www.maycoss@gmail.com","JUCERR"),
    ("Wesley Silva Ramos","wesleyleiloeiro@gmail.com","JUCERR"),
    # ── JUCESC ────────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCESC"),
    ("Anderson Douglas Gali Falleiros","contato@falleirosleiloes.com.br","JUCESC"),
    ("Aridina Maria Do Amaral","contato@formulaleiloes.com.br","JUCESC"),
    ("Catiele Borges Leffa","leffa@leffaleiloes.com.br","JUCESC"),
    ("CLEVER ELMES MILANI","contato@milanileiloes.com.br","JUCESC"),
    ("Cristiane Borguetti Moraes Lopes","atendimento@lopesleiloes.com.br","JUCESC"),
    ("CRISTIANO DA ROSA SCHONTAG","contato@trileiloes.com.br","JUCESC"),
    ("DAIANE FUCKS PELENTIR","daiane@agilileiloes.com.br","JUCESC"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCESC"),
    ("Daniel Melo Cruz","contato@grupolance.com.br","JUCESC"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com","JUCESC"),
    ("DIEGO COSTA MULLER","contato@mullerleiloes.com.br","JUCESC"),
    ("DIEGO WOLF DE OLIVEIRA","contato@diegoleiloes.com.br","JUCESC"),
    ("DiÓrgenes ValÉrio Jorge","contato@catarinenseleiloes.com.br","JUCESC"),
    ("Dora Plat","dplat@portalzuk.com.br","JUCESC"),
    ("Eduardo Abreu Alves Barbosa","eduardo.abreu@bestleiloes.com.br","JUCESC"),
    ("Eduardo De Werk","eduardo@gestordeleiloes.com.br","JUCESC"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCESC"),
    ("ELTON LUIZ SIMON","elton@simonleiloes.com.br","JUCESC"),
    ("EUCLIDES MARASCHI JUNIOR","marascajr@hastapublica.com.br","JUCESC"),
    ("Everton Dias Medeiros","contato@diasleiloes.com.br","JUCESC"),
    ("Fabiane Tissiane Baldissera De Souza","fabiane@baldisseraleiloeiros.com.br","JUCESC"),
    ("Felipe Gonzaga Daux","contato@daux.com.br","JUCESC"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCESC"),
    ("FRANCISCO HILLESHEIM","contato@alemaoleiloeiro.com.br","JUCESC"),
    ("Gabriel Mazzolli Damiani","suporte@mazzollileiloes.com.br","JUCESC"),
    ("Giovano Ávila Alves","contato@soleiloes.com.br","JUCESC"),
    ("Giovanni Silva Wersdoefer","hastapublica@hastapublica.lel.br","JUCESC"),
    ("GUILHERME EDUARDO STUTZ TOPOROSKI","contato@topoleiloes.com.br","JUCESC"),
    ("GUSTAVO MORETTO GUIMARÃES DE OLIVEIRA","contato@gustavomorettoleiloeiro.com.br","JUCESC"),
    ("HELCIO KRONBERG","helcio@kronbergleiloes.com.br","JUCESC"),
    ("Janine Ledoux Krobel Lorenz","leiloeira@krobelleiloes.com.br","JUCESC"),
    ("Jefferson Eduardo Zampieri","zampieri@zampierileilao.com.br","JUCESC"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCESC"),
    ("JORGE FERLIN DALE NOGARI DOS SANTOS","gerencia@nogari.com.br","JUCESC"),
    ("José Sérgio Della Giustina","CONTATO@MACEDOLEILOES.COM.BR","JUCESC"),
    ("LEVY DOS SANTOS MORAES FILHO","santosmoraesleiloes@gmail.com","JUCESC"),
    ("LUAN UBIALLI","LUAN@UBIALLILEILOES.COM.BR","JUCESC"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCESC"),
    ("Luciano Resende Rodrigues","isabellagmleilao@gmail.com","JUCESC"),
    ("Lúcio Ubialli","ubialli@centralsuldeleiloes.com.br","JUCESC"),
    ("Luiz Balbino Da Silva Junior","contato@globoleiloes.com.br","JUCESC"),
    ("LUIZ BARBOSA DE LIMA JUNIOR","LUIZB.LIMA@YMAIL.COM","JUCESC"),
    ("Magnun Luiz Serpa","contato@serpaleiloes.com.br","JUCESC"),
    ("Marcelo Drechsel","contato@luminaleiloes.com.br","JUCESC"),
    ("Marcus Rogério Araújo Samoel","contato@deltaleiloes.com.br","JUCESC"),
    ("Marcus Vinicius Yoshimi Uebara","contato@destakleiloes.com.br","JUCESC"),
    ("Marileia May","contato@leialeiloes.com.br","JUCESC"),
    ("MÁRIO LESSA FREITAS FILHO","contato@lessaleiloes.com.br","JUCESC"),
    ("MICHELE PACHECO DA ROSA SANDOR","contato@expressoleiloes.com.br","JUCESC"),
    ("Mouzar Baston Filho","mouzar@bastonleiloes.com.br","JUCESC"),
    ("Nelcir Aparecida Catafesta","leiloeira@nelcileiloes.com.br","JUCESC"),
    ("NEILA ROSANE RIBEIRO DOS SANTOS","intimacoes@nsleiloes.lel.br","JUCESC"),
    ("NORTON JOCHIMS FERNANDES","grandesleiloes@terra.com.br","JUCESC"),
    ("Odiclesio Jaison Storchio","leiloeiro@oesteleiloes.com.br","JUCESC"),
    ("Patricia Pimentel Grocoski Costa","contato@pimentelleiloes.com.br","JUCESC"),
    ("Paulo Castelan Minatto","paulo@casadoleilao.com","JUCESC"),
    ("Paulo Pizzolatti Neto","paulo@topleiloes.com.br","JUCESC"),
    ("RAFAEL CERETTA ALEGRANZZI","contato@alegranzzileiloes.com.br","JUCESC"),
    ("Renan Souza Silva","contato@silvaleiloes.com.br","JUCESC"),
    ("Renato Schlobach Moyses","renato.moyses@rmoyses.com.br","JUCESC"),
    ("Ricardo Bampi","leilao@ricardobampi.com.br","JUCESC"),
    ("RICARDO FERREIRA GOMES","contato@ricardogomesleiloes.com.br","JUCESC"),
    ("Rodolfo Da Rosa Schontag","CONTATO@LEILOEIROPUBLICO.COM.BR","JUCESC"),
    ("Roger Wenning","contato@reidosleiloes.com.br","JUCESC"),
    ("Rogério Damiani","rogerio@damianileiloes.com.br","JUCESC"),
    ("Rodrigo Schmitz","contato@hleiloes.com","JUCESC"),
    ("RODRIGO ZAGO SZORTYKA","contato@szortykaleiloes.com.br","JUCESC"),
    ("RUDIVAL ALMEIDA GOMES JUNIOR","rudival@vipleiloes.com.br","JUCESC"),
    ("Ruy Walter Baldissera","baldissera@baldisseraleiloeiros.com.br","JUCESC"),
    ("Sabrina Da Silva Pereira Eckelberg","contato@sabrinaleiloes.com.br","JUCESC"),
    ("Simone Wenning","simone@masterleiloes.com.br","JUCESC"),
    ("Soraya Nass Nart","contato@assertivaleiloes.com.br","JUCESC"),
    ("TIAGO LOPES ALEGRANZZI","TIAGOALEGRANZZI@HOTMAIL.COM","JUCESC"),
    ("ULISSES DONIZETE RAMOS","contato@donizetteleiloes.com.br","JUCESC"),
    ("Viviane Aparecida Brassiani Engicht","contato@brassianileiloes.com.br","JUCESC"),
    ("WERNO KLÖCKNER JÚNIOR","werno@kleiloes.com.br","JUCESC"),
    # ── JUCESP ────────────────────────────────────────────────────────────────
    ("Alberto José Marchi Macedo","alberto@albertomacedoleiloes.com.br","JUCESP"),
    ("Alessandra Cristhina Macedo De Freitas","ale.macedo@freitasleiloeiro.com.br","JUCESP"),
    ("Alessandro De Assis Teixeira","contato@leiloesjudiciaismg.com.br","JUCESP"),
    ("Alex Willian Hoppe","licitacoes@hoppeleiloes.com.br","JUCESP"),
    ("Alexsandro Batista","atendimento@batistaleiloes.com.br","JUCESP"),
    ("Alfio Carlos Affonso Zalli Neto","contato@tezaleiloes.com.br","JUCESP"),
    ("Alethea Carvalho Lopes","alethea@vivaleiloes.com.br","JUCESP"),
    ("Amanda Tomazelli Pereira","amanda@ricoleiloes.com.br","JUCESP"),
    ("Andre Sobreira Da Silva","atendimento@centraljudicial.com.br","JUCESP"),
    ("Angela Eiko Inoue Dos Santos","atendimento@extrajustleiloes.com.br","JUCESP"),
    ("Angela Pecini Silveira","angela@pecinileiloes.com.br","JUCESP"),
    ("Angela Saraiva Portes Souza","angela@saraivaleiloes.com.br","JUCESP"),
    ("Angelica Mieko Inoue Dantas","lancetotal@lancetotal.com.br","JUCESP"),
    ("Antonio Carlos Celso Santos Frazao","acf1234@hotmail.com","JUCESP"),
    ("Antonio Hissao Sato Júnior","diretoria@satoleiloes.com.br","JUCESP"),
    ("Antonio Luiz Guariglia","antonio@guariglia.com.br","JUCESP"),
    ("Arnold Strass","leiloes@savoyleiloes.com.br","JUCESP"),
    ("Brian Galvao Frota","brian@gfleiloes.com.br","JUCESP"),
    ("Bruno Silva Santucci","contato@nextleiloes.com.br","JUCESP"),
    ("Caio Marcos Campos Caldeira","caioleiloeirooficial@outlook.com","JUCESP"),
    ("Carlo Ferrari","contato@carloferrarileiloes.com.br","JUCESP"),
    ("Carlos De Jesus Ramos Ribeiro","contato@rmcleiloes.com.br","JUCESP"),
    ("Carlos Eduardo Sorgi Da Costa","atendimento@eduardosorgileiloeiro.com.br","JUCESP"),
    ("Carla Sobreira Umino","atendimento@lancenoleilao.com.br","JUCESP"),
    ("CARLOS CHUI","contato@arremataronline.com.br","JUCESP"),
    ("Cezar Augusto Badolato Silva","cezar.silva@leilaovip.com.br","JUCESP"),
    ("Cibelle Simonetti Sales","cibelle@rocketleiloes.com.br","JUCESP"),
    ("Claudio Sousa Dos Santos","claudio@allianceleiloes.com.br","JUCESP"),
    ("Clecio Oliveira De Carvalho","clecio@leilaooficialonline.com.br","JUCESP"),
    ("Cleia Lucia Satiko Hirassawa Chui","chuileiloes@chuileiloes.com.br","JUCESP"),
    ("Conceicao Maria Fixer","contato@mariafixerleiloes.com.br","JUCESP"),
    ("Cristiane Borguetti Moraes Lopes","cristiane@lopesleiloes.com.br","JUCESP"),
    ("Dagmar Conceicao De Souza Flores","dagmar@leilaobrasil.com.br","JUCESP"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCESP"),
    ("Daniel Melo Cruz","contato@grupolance.com.br","JUCESP"),
    ("Danillo Fabricio Ballini Miani","danillo@dbmleiloes.com.br","JUCESP"),
    ("Danilo Cardoso Da Silva","danilo.cardoso@milanleiloes.com.br","JUCESP"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com.br","JUCESP"),
    ("Denys Pyerre De Oliveira","contato@leje.com.br","JUCESP"),
    ("Dora Plat","dplat@portalzuk.com.br","JUCESP"),
    ("Douglas Jose Fidalgo","douglas@fidalgoleiloes.com.br","JUCESP"),
    ("Eder Amaral De Oliveira","eder@amaralleiloes.com.br","JUCESP"),
    ("Eduardo Consentino","contato@biasileiloes.com.br","JUCESP"),
    ("Eduardo Da Silva Pinto","contato@tribunaleiloes.com.br","JUCESP"),
    ("Eduardo Dos Reis","eduardo@casareisleiloes.com.br","JUCESP"),
    ("Eduardo Jordao Boyadjian","jordao@jordaoleiloes.com.br","JUCESP"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCESP"),
    ("Emerson Lopes Cardoso","contato@cardosoleiloes.com.br","JUCESP"),
    ("EUCLIDES MARASCHI JUNIOR","marascajr@hastapublica.com.br","JUCESP"),
    ("Fabiana Cusato","juridico@unileiloes.com.br","JUCESP"),
    ("Fabio Prando Fagundes Goes","fabiopfgoes@gmail.com","JUCESP"),
    ("Farah Catarina Vasconcelos De Santi","farah@desantileiloes.com.br","JUCESP"),
    ("Felipe Nunes Gomes Teixeira Bignardi","felipe@leiloei.com","JUCESP"),
    ("Felipe Rodrigues De Souza","felipe.souza@leilaoeletronico.com.br","JUCESP"),
    ("Fernanda De Mello Franco","fernanda@francoleiloes.com.br","JUCESP"),
    ("Fernando Cabecas Barbosa","adm@grupoarremateleiloes.com.br","JUCESP"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCESP"),
    ("Fernando Chui","fernando@chuileiloes.com.br","JUCESP"),
    ("Fernando Jose Cerello Goncalves Pereira","fernando@megaleiloes.com.br","JUCESP"),
    ("Fernando Sacco Neto","fernando@vivaleiloes.com.br","JUCESP"),
    ("Flavio Cunha Sodre Santoro","airton.silva@sodresantoro.com.br","JUCESP"),
    ("Francisco Donizetti Tripoloni","francisco@tripolonileiloes.com.br","JUCESP"),
    ("Frederico Alberto Severino Frazao","frederico@maisleilao.com.br","JUCESP"),
    ("Galvez Goncalves","galvez.leiloeiro@gmail.com","JUCESP"),
    ("George Henrique Ribeiro Benozzati","george@benozzati.com.br","JUCESP"),
    ("GILSON KENITI INUMARU","contato@gilsonleiloes.com.br","JUCESP"),
    ("GIORDANO BRUNO COAN AMADOR","giordano@giordanoleiloes.com.br","JUCESP"),
    ("Guilherme De Oliveira Rossi","guilhermerossi@rossileiloes.com.br","JUCESP"),
    ("GUILHERME EDUARDO STUTZ TOPOROSKI","contato@topoleiloes.com.br","JUCESP"),
    ("Guilherme Roberto Dorta Da Silva","guilherme@dortaadv.com.br","JUCESP"),
    ("Gustavo Cristiano Samuel Dos Reis","gustavo.reis@gustavoreisleiloes.com.br","JUCESP"),
    ("Gustavo De Oliveira Rossi","gustavo@rossileiloes.com.br","JUCESP"),
    ("Gustavo Moretto Guimaraes De Oliveira","contato@gustavomorettoleiloeiro.com.br","JUCESP"),
    ("HELCIO KRONBERG","helcio@kronbergleiloes.com.br","JUCESP"),
    ("Hugo Leonardo Alvarenga Cunha","contato@cunhaleiloeiro.com.br","JUCESP"),
    ("Igor Barros De Miranda Carvalho","contato@lancejudicial.com.br","JUCESP"),
    ("Irani Flores","irani.flores@leilaobrasil.com.br","JUCESP"),
    ("Izabella Melo Ferreira Praes","juridico02@palaciodosleiloes.com.br","JUCESP"),
    ("Joel Augusto Picelli Filho","joel@picellileiloes.com.br","JUCESP"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCESP"),
    ("Jonas Rymer","jonasrymer01@gmail.com","JUCESP"),
    ("Jorge Luiz Molgado","jorge@molgado.com.br","JUCESP"),
    ("Jose Eduardo De Abreu Sodre Santoro","airton.silva@sodresantoro.com.br","JUCESP"),
    ("Jose Ricardo Ferreira","jricardo@jrfleiloes.com.br","JUCESP"),
    ("Jose Roberto Neves Amorim","nevesamorim@D1lance.com","JUCESP"),
    ("Jose Valero Santos Junior","contato@valeroleiloes.com.br","JUCESP"),
    ("Julio Abdo Costa Calil","julio.calil@clilleiloes.com.br","JUCESP"),
    ("Julio Paques Neto","spartes.contato@gmail.com","JUCESP"),
    ("Jussiara Santos Ermano Sukiennik","leiloeira@jussiaraleiloes.com","JUCESP"),
    ("Katia Christina Macedo De Freitas","katia.macedo@freitasleiloeiro.com.br","JUCESP"),
    ("Leonardo De Campos Penin","contato@lecape.com.br","JUCESP"),
    ("Leonardo Vieira Amaral","leon.lv2015@gmail.com","JUCESP"),
    ("Ligia Seixas","ligia@bidmax.com.br","JUCESP"),
    ("Lidianicy Xavier De Lima","judicial@sublimeleiloes.com.br","JUCESP"),
    ("Luis Alexandre Andrade","andradeleiloes@andradeleiloes.com.br","JUCESP"),
    ("Luis Fernando Battaglia","contato@battaglialeiloeiro.com.br","JUCESP"),
    ("Luiz Fernando Moreira Dutra","dutra@dutraleiloes.com.br","JUCESP"),
    ("Marcus Vinicius Yoshimi Uebara","vinicius@destakleiloes.com.br","JUCESP"),
    ("Marcelo Fuad Cavalli Yarid","marceloyarid@bigleiloes.com.br","JUCESP"),
    ("Marcelo Valland","marcelo@pactoleiloes.com.br","JUCESP"),
    ("Marco Antonio Barbosa De Oliveira Junior","contato@marcoantonioleiloeiro.com.br","JUCESP"),
    ("Marcos Roberto Torres","leiloeiro@3torresleiloes.com.br","JUCESP"),
    ("Marilaine Borges De Paula","leiloeiro@e-confiancaleiloes.com.br","JUCESP"),
    ("Marta Simone Shiokawa","contato@mleiloes.com.br","JUCESP"),
    ("MAURICIO SAMBUGARI APPOLINARIO","andraleiloes@andraleiloes.com.br","JUCESP"),
    ("Mauricio Jose De Sousa Costa","contato@mjleiloes.com.br","JUCESP"),
    ("Mauro Zukerman","mauro@zukerman.com.br","JUCESP"),
    ("Miriam Aparecida Trindade Gir","617.miriam@conceitoleiloes.com.br","JUCESP"),
    ("Mouzar Baston Filho","mouzar@bastonleiloes.com.br","JUCESP"),
    ("Murilo Paes Lopes Lourenco","murilo@leilaobrasil.com.br","JUCESP"),
    ("Otavio Lauro Sodre Santoro","airton.silva@sodresantoro.com.br","JUCESP"),
    ("Otavio Martins Colucci","contato@omcleiloes.com.br","JUCESP"),
    ("Patricia Avelar Monteiro Fidalgo","financeiro@fidalgoleiloes.com.br","JUCESP"),
    ("Paulo Cesar De Carvalho","cesarcarvalho@nossoleilao.com.br","JUCESP"),
    ("Persio Boschetti Junior","persio@deseulance.com","JUCESP"),
    ("Rafael Brambila Peixoto","contato@peixotoleiloes.com.br","JUCESP"),
    ("Rafael Cicolin","rafa.cicolin@gmail.com","JUCESP"),
    ("Rafaela Melo Ferreira Marzano","juridico02@palaciodosleiloes.com.br","JUCESP"),
    ("Regina Teresa Franci Brotto","regina@brottoleiloes.com.br","JUCESP"),
    ("Renan Souza Silva","contato@souzasilvaleiloes.com.br","JUCESP"),
    ("Renato Gracie","renato@gracieleiloes.com.br","JUCESP"),
    ("Renato Schlobach Moyses","contato@rmoyses.com.br","JUCESP"),
    ("Ricardo Lucas Granado Da Silva","atendimento@granadoleiloes.com.br","JUCESP"),
    ("Ricardo Miranda De Souza","ricardo@jordaoleiloes.com.br","JUCESP"),
    ("Rodrigo Aparecido Rigolon da Silva","contato@rigolonleiloes.com.br","JUCESP"),
    ("Rogerio Damasio De Oliveira","rogerioef@gmail.com","JUCESP"),
    ("Romualdo Pandolfo","contato@totalleiloes.com.br","JUCESP"),
    ("Ronaldo Milan","ronaldo@milanleiloes.com.br","JUCESP"),
    ("Rosana Lemos Da Costa","contato@ricoleiloes.com.br","JUCESP"),
    ("Sami Raicher","sami@raicherleiloes.com.br","JUCESP"),
    ("Sergio Villa Nova De Freitas","sergio@freitasleiloeiro.com.br","JUCESP"),
    ("Silvia Dau Pelloni De Souza","casaamarela@casaamarelaleiloes.com.br","JUCESP"),
    ("Silvia De Castro Marques","contato@silvaleiloes.com.br","JUCESP"),
    ("Silvio Cesar De Jesus Santos","contato@editalleiloes.com.br","JUCESP"),
    ("Spartaco Santi Junior","contato@spartacoleiloes.com.br","JUCESP"),
    ("Tatiana Hisa Sato","tatiana.hisa@satoleiloes.com.br","JUCESP"),
    ("Thais Silva Moreira De Sousa","thais@tmleiloes.com.br","JUCESP"),
    ("Tiago Clemente Sampaio","tsampaio@multipliqueleiloes.com.br","JUCESP"),
    ("Tiago Tessler Blecher","tiago.tessler@webleiloes.com.br","JUCESP"),
    ("Uilian Aparecido Da Silva","contato@goldleiloes.com.br","JUCESP"),
    ("Ugo Rossi Filho","ugo@rossileiloes.com.br","JUCESP"),
    ("Viviane Maria Goncalves Da Silva","leiloes@savoyleiloes.com.br","JUCESP"),
    ("Wagner Lotti","contato@lottileiloes.com.br","JUCESP"),
    ("Wanderley Samuel Pereira","wanderley@wspleiloes.com.br","JUCESP"),
    ("Wesley Oliveira Ascanio","wesley.ascanio@gmail.com","JUCESP"),
    ("Willian Pereira Teixeira Quenca","atendimento@willianquencaleiloeiro.com.br","JUCESP"),
    # ── JUCETINS ──────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCETINS"),
    ("Camilla Correia Vecchi Aguiar","vecchileiloes@gmail.com","JUCETINS"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCETINS"),
    ("Davi Borges De Aquino","contato@alfaleiloes.com","JUCETINS"),
    ("Eduardo Gomes","contato@leiloeiroeduardo.com.br","JUCETINS"),
    ("Fernando Caetano Moreira Filho","fernando@fernandoleiloeiro.com.br","JUCETINS"),
    ("Joabe Balbino Da Silva","joabe@globoleiloes.com.br","JUCETINS"),
    ("Jonas Gabriel Antunes Moreira","jonas@jonasleiloeiro.com.br","JUCETINS"),
    ("Leonardo Coelho Avelar","arrematabem@arrematabem.com.br","JUCETINS"),
    ("Lívia Leilane De Oliveira Azevedo","livia@livialeiloes.com.br","JUCETINS"),
    ("Lucas Rafael Antunes Moreira","lucas@lucasleiloeiro.com.br","JUCETINS"),
    ("Marciano Aguiar Carneiro","marcianoleiloes@gmail.com","JUCETINS"),
    ("Mouzar Baston Filho","sac@bastonleiloes.com.br","JUCETINS"),
    ("Murilo Gonçalves Ramos","murilo-ramos@hotmail.com","JUCETINS"),
    ("Rodolfo Da Rosa Schontag","CONTATO@LEILOEIROPUBLICO.COM.BR","JUCETINS"),
    ("Rudival Almeida Gomes Júnior","rudival@rjleiloes.com.br","JUCETINS"),
    ("Sandro De Oliveira","olsandro@yahoo.com.br","JUCETINS"),
    ("Tiago Tessler Blecher","tiago.tessler@webleiloes.com.br","JUCETINS"),
    ("Victor Oliveira Dorta","victorodortaleiloes@gmail.com","JUCETINS"),
    # ── JUCISDF ───────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCISDF"),
    ("ANA CAROLINA BRASIL DE OLIVEIRA MAIA","contato@anabrasilleiloes.com.br","JUCISDF"),
    ("ANDRE GUSTAVO BOUCAS IGNACIO","brasilialeiloes@hotmail.com","JUCISDF"),
    ("ANTONIO HISSAO SATO JUNIOR","judicial@satoleiloes.com.br","JUCISDF"),
    ("Caroline De Sousa Ribas","caroline@liderleiloes.com.br","JUCISDF"),
    ("Cesar Augusto Bagatini","federalleiloes@gmail.com","JUCISDF"),
    ("Cristiane Borguetti Moraes Lopes","atendimento@lanceja.com.br","JUCISDF"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCISDF"),
    ("DAVI BORGES AQUINO","contato@alfaleiloes.com","JUCISDF"),
    ("DENISE ARAUJO DOS SANTOS","denise.leiloes@gmail.com","JUCISDF"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCISDF"),
    ("Erico Sobral Soares","ericosobralsoares@gmail.com","JUCISDF"),
    ("Fábio Manoel Guimarães","contato@fabioleiloes.com.br","JUCISDF"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCISDF"),
    ("Fernando Chui","fernando@chuileiloes.com.br","JUCISDF"),
    ("FREDERICO GUSTAVO FONSECA IUNES","eixoleiloes@gmail.com","JUCISDF"),
    ("GIAN ROBERTO CAGNI BRAGGIO","gian@braggio.com.br","JUCISDF"),
    ("Giovano Ávila Alves","GIOVANO@SOLEILOES.COM.BR","JUCISDF"),
    ("GUILHERME EDUARDO STUTZ TOPOROSKI","contato@topoleiloes.com.br","JUCISDF"),
    ("GUSTAVO MORETTO GUIMARÃES DE OLIVEIRA","contato@gustavomorettoleiloeiro.com.br","JUCISDF"),
    ("HELCIO KRONBERG","helcio@krobergleiloes.com.br","JUCISDF"),
    ("Irani Flores","irani.flores@leilaobrasil.com.br","JUCISDF"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCISDF"),
    ("José Luiz Pereira Vizeu","joseluiz@flexleiloes.com.br","JUCISDF"),
    ("Leonardo Coelho Avelar","arrematabem@arrematabem.com.br","JUCISDF"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCISDF"),
    ("Marcelo Valland","contato@valland.com.br","JUCISDF"),
    ("Marcus Vinicius Yoshimi Uebara","licitacao@destakleiloes.com.br","JUCISDF"),
    ("Mouzar Baston Filho","mouzar@bastonleiloes.com.br","JUCISDF"),
    ("Orlando Araujo Dos Santos","contato@oaleiloes.com.br","JUCISDF"),
    ("Otavio Lauro Sodré Santoro","comercial@sodresantoro.com.br","JUCISDF"),
    ("OZIAS TAVARES PEREIRA","oziasleiloeiro@gmail.com","JUCISDF"),
    ("Paulo Alexandre Heisler","pauloalexandreheisler@gmail.com","JUCISDF"),
    ("PAULO HENRIQUE DE ALMEIDA TOLENTINO","contato@paulotolentino.com.br","JUCISDF"),
    ("Rodrigo Aparecido Rigolon da Silva","contato@rigolonleiloes.com.br","JUCISDF"),
    ("Rodolfo Da Rosa Schontag","CONTATO@LEILOEIROPUBLICO.COM.BR","JUCISDF"),
    ("Rodrigo Schmitz","contato@hleiloes.com","JUCISDF"),
    ("Rossana Paiva Borges De Oliveira","rossana@caiapoleiloes.com.br","JUCISDF"),
    ("Sandro De Oliveira","olsandro@yahoo.com.br","JUCISDF"),
    ("SILVIA HELENA BALBINO BARROS PALMA","silvia@portalleilomaster.com.br","JUCISDF"),
    ("Tatiana Paula Zani De Sousa","tatianasousa@liderleiloes.com.br","JUCISDF"),
    ("Wesley Oliveira Ascanio","wesley@tabaleiloes.com.br","JUCISDF"),
    # ── JUCISRS ───────────────────────────────────────────────────────────────
    ("Alex Willian Hoppe","contato@hoppeleiloes.com.br","JUCISRS"),
    ("ALEXANDRE RECH","contato@rechleiloes.com.br","JUCISRS"),
    ("Alvaro Marques Teixeira","alvaroleiloes@gmail.com","JUCISRS"),
    ("Anderson Douglas Gali Falleiros","contato@falleirosleiloes.com.br","JUCISRS"),
    ("AUGUSTO PARMEGGIANI PESTANA MARQUES GOMES","augusto@pestanaleiloes.com.br","JUCISRS"),
    ("Catiele Borges Leffa","leffa@leffaleiloes.com.br","JUCISRS"),
    ("CESAR CARLOS RABUSKE","rabuskeleiloes@uol.com.br","JUCISRS"),
    ("CRISTIANO DA ROSA SCHONTAG","cristianoschontag@gmail.com","JUCISRS"),
    ("DAIANE FUCKS PELENTIR","daiane@agilileiloes.com.br","JUCISRS"),
    ("Daniel Elias Garcia","contato@dgleiloes.com.br","JUCISRS"),
    ("Davi Borges De Aquino","inscricoes@alfaleiloes.com","JUCISRS"),
    ("Denys Pyerre De Oliveira","contato@leje.com.br","JUCISRS"),
    ("DIONIR BIANCHI","dionir@bianchileiloes.com.br","JUCISRS"),
    ("Eduardo Abreu Alves Barbosa","atendimento01@bestleiloes.com.br","JUCISRS"),
    ("Eduardo Schmitz","comercial@clicleiloes.com.br","JUCISRS"),
    ("EUCLIDES MARASCHI JUNIOR","marascajr@hastapublica.com.br","JUCISRS"),
    ("FABIO SAMIR MACHADO","machadoleiloes@yahoo.com","JUCISRS"),
    ("Fernando Caetano Moreira Filho","secretario8@fernandoleiloeiro.com.br","JUCISRS"),
    ("FRANCISCO HILLESHEIM","francisco@alemaoleiloeiro.com.br","JUCISRS"),
    ("GABRIEL SILVA DA ROSA","gabriel@gabrielleiloes.com.br","JUCISRS"),
    ("GIANCARLO PETERLONGO LORENZINI MENEGOTTO","peterlongoleiloes@peterlongoleiloes.com.br","JUCISRS"),
    ("GUILHERME EDUARDO STUTZ TOPOROSKI","CREDENCIAMENTO@TOPOLEILOES.COM.BR","JUCISRS"),
    ("GUSTAVO TURANI","contato@turanileiloes.com.br","JUCISRS"),
    ("HÉlcio Kronberg","helcio@kronbergleiloes.com.br","JUCISRS"),
    ("JEFÃRSON BENEDETTO","contato@benedettoleiloes.com.br","JUCISRS"),
    ("JOACIR MONZON POUEY","joacirleiloesmp@gmail.com","JUCISRS"),
    ("JOEL DA SILVA REIS","joel@joelreisleiloes.com.br","JUCISRS"),
    ("Jonas Gabriel Antunes Moreira","jonasleiloeiro@yahoo.com.br","JUCISRS"),
    ("JORGE FERLIN DALE NOGARI DOS SANTOS","adm@nogari.com.br","JUCISRS"),
    ("Josecelli Kildare Fraga Gomes","kildare@kildareleiloes.com.br","JUCISRS"),
    ("JOYCE RIBEIRO","joyce@leiloesjudiciaisrs.com.br","JUCISRS"),
    ("Lucas Rafael Antunes Moreira","lucasleiloeiro@hotmail.com","JUCISRS"),
    ("LUCIANO SCHEID","contato@scheidleiloes.com.br","JUCISRS"),
    ("LUIZ BARBOSA DE LIMA JUNIOR","LUIZB.LIMA@YMAIL.COM","JUCISRS"),
    ("MAURICIO RODRIGO BACK","mauricio@backleiloes.com.br","JUCISRS"),
    ("MAURICIO GEHM","mauricioleiloes@hotmail.com","JUCISRS"),
    ("MAURO PEREIRA DE OLIVEIRA","mauroleiloeiro@terra.com.br","JUCISRS"),
    ("NEILA ROSANE RIBEIRO DOS SANTOS","neilaleiloeira.arquivo@gmail.com","JUCISRS"),
    ("NORTON JOCHIMS FERNANDES","grandesleiloes@terra.com.br","JUCISRS"),
    ("ODICLESIO JAISON STORCHIO","leiloeiro@oesteleiloes.com.br","JUCISRS"),
    ("Paulo Alexandre Heisler","pauloalexandreheisler@gmail.com","JUCISRS"),
    ("PEDRO MESQUITA DA CRUZ","pedro@evolveleiloes.com","JUCISRS"),
    ("Pietrangelo Rosalem","pietrangelorosalem@gmail.com","JUCISRS"),
    ("RAFAEL CERETA ALEGRANZZI","contato@alegranzzileiloes.com.br","JUCISRS"),
    ("Renato Schlobach Moyses","intimacao@rmoyses.com.br","JUCISRS"),
    ("Rodolfo Da Rosa Schontag","CONTATO@LEILOEIROPUBLICO.COM.BR","JUCISRS"),
    ("RODRIGO ZAGO SZORTYKA","contato@szortykaleiloes.com.br","JUCISRS"),
    ("RUDIVAL ALMEIDA GOMES JUNIOR","rudival@rjleiloes.com.br","JUCISRS"),
    ("Sidney Belarmino Ferreira Junior","sidney@sfleiloes.com.br","JUCISRS"),
    ("Tiago Tessler Blecher","credenciamento@webleiloes.com.br","JUCISRS"),
    ("ULISSES DONIZETE RAMOS","leiloeiro@donizetteleiloes.com.br","JUCISRS"),
]

HEADER = ["Nome completo","E-mail Principal","Situação","Junta Comercial"]

def main():
    rows = [
        {"Nome completo": nome, "E-mail Principal": email,
         "Situação": "REGULAR", "Junta Comercial": junta}
        for nome, email, junta in DATA
    ]

    with open(OUT, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=HEADER)
        w.writeheader()
        w.writerows(rows)

    print(f"Gerado: {OUT}")
    print(f"  {len(rows)} entradas | {len({r['E-mail Principal'].split('@')[1] for r in rows if '@' in r['E-mail Principal']})} domínios únicos")

if __name__ == "__main__":
    main()
